networks:
  chatbot-network:
    driver: bridge

services:
  api_large:
    image: ejsheldon/api_large:0.0.1 
    environment:
      APP_PORT: "8000"
    ports:
      - 8000:8000
    networks:
      - chatbot-network
  
  api_intro:
    image: ejsheldon/api_small:0.1.0 
    environment:
      APP_PORT: "5050"
    ports:
      - 5050:5050
    networks:
      - chatbot-network

    # network_mode: host
  chatbot_flask:
    image: ejsheldon/chatbot_flask:0.1.0
    ports:
      - 5000:5000
    networks:
      - chatbot-network
    